version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: monitoring-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_passwd
      MYSQL_DATABASE: monitoringequipment
      MYSQL_USER: konstlabel
      MYSQL_PASSWORD: 23581321
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: monitoring-app:latest
    container_name: monitoring-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/monitoringequipment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: konstlabel
      SPRING_DATASOURCE_PASSWORD: 23581321

      cors.allowedOrigins: http://localhost:3000
    networks:
      - backend
    ports:
      - "53828:53828"

  nginx:
    image: nginx:stable-alpine
    container_name: monitoring-nginx
    restart: always
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
