version: "3.8"

services:

  db:
    image: mysql:8.0
    container_name: monitoring-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_passwd
      MYSQL_DATABASE: monitoring_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app_passwd
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: monitoring-app:latest
    container_name: monitoring-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: >-
        jdbc:mysql://db:3306/monitoring_db
        ?useSSL=false
        &serverTimezone=UTC
        &allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: app_passwd
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - backend
    # не прокидываем порт наружу — контакты только через nginx
    # (если хотите обойтись без nginx, раскомментируйте строку ниже)
    # ports:
    #   - "8080:8080"

  nginx:
    image: nginx:stable-alpine
    container_name: monitoring-nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
